services:
  api:
    build: .
    image: travissscottt/api-image-2:latest
    container_name: api-container
    ports:
      - "8000:8000"
    networks:
    - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb-container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge