pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('travissscottt-dockerhub')
    }

    options {
        timestamps()
        skipDefaultCheckout(true)
    }

    triggers {
        pollSCM('H/5 * * * *')
    }

    stages {

        stage('Clone GitHub Repository') {
            steps {
                cleanWs()
                sh 'git clone -b master https://github.com/Dolmachi/CI-CD-pipeline-Lab-1.git'
            }
        }

        stage('Download Data with DVC') {
            steps {
                dir("CI-CD-pipeline-Lab-1") {
                    sh 'dvc pull'
                }
            }
        }

        stage('Checkout Repo Dir') {
            steps {
                sh 'cd CI-CD-pipeline-Lab-1 && ls -la'
            }
        }

        stage('Run Unit Tests') {
            steps {
                dir("CI-CD-pipeline-Lab-1") {
                    sh '''
                        source ~/miniconda3/etc/profile.d/conda.sh
                        conda activate mlops
                        pytest --cov=src
                    '''
                }
            }
        }

        stage('Login to DockerHub') {
            steps {
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
            }
        }

        stage('Build and Run Docker Container') {
            steps {
                script {
                    try {
                        sh 'cd CI-CD-pipeline-Lab-1 && docker compose build'
                    } finally {
                        sh '''
                            cd CI-CD-pipeline-Lab-1
                            docker compose up -d
                        '''
                    }
                }
            }
        }

        stage('Check Container Logs') {
            steps {
                dir("CI-CD-pipeline-Lab-1") {
                    sh '''
                        container_id=$(docker ps -qf "name=api_container")
                        if [ -z "$container_id" ]; then
                            echo "No container running"
                            exit 1
                        fi
                        docker logs --tail 1000 "$container_id"
                    '''
                }
            }
        }

        stage('Push Docker Image to DockerHub') {
            steps {
                sh '''
                    image_id=$(docker images -q travissscottt/api_car_price:latest)
                    if [ -z "$image_id" ]; then
                        echo "Error: Docker image not found. Build might have failed."
                        exit 1
                    fi
                    docker push travissscottt/api_car_price:latest
                '''
            }
        }
    }

    post {
        always {
            sh 'docker stop api_container'
            sh 'docker rm api_container'
            sh 'docker rmi travissscottt/api_car_price:latest'
            sh 'docker logout'
            cleanWs()
        }
    }
}


